### PR TITLE
Updates for reflex-dom-0.5

### PR DESCRIPTION
**Pull request by imalsogreg**
Most of of the changes in this PR are small adjustments for changes in the ghcjs-dom API - a lot of functions take `ToJSVal a => a` rather than `JSVal`, or return `a` instead of `Maybe a`.

The hard part, which I haven't figured out, is how to deal with the `onSuccess` and `onUpgradeNeeded` callbacks. I just don't understand this part of the reflex host yet.

### CODE REVIEW

**Comment by imalsogreg** [comment]
The test app starts up well, and it creates the `todo` table.
Putting `12` into the text box and hitting the `+` button, the debugging string says:
`Waiting..Upgarding..Trans err: "Closed"`

**Comment by mageshb** [comment]
It maybe due to the fact that ```onSuccess``` callback is commented out.
Some of the event trigger code was written with respect to old reflex.
I will look into that.

**Comment by mageshb** [comment]
Pushed a commit which fixes the issue.
Now the sample code in the test, insert values as expected.

**Comment by imalsogreg** [comment]
@mageshb Excellent, thank you!

**Pull request merged**
